//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Klienci
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Klienci()
        {
            this.Wypozyczenia = new HashSet<Wypozyczenia>();
        }
    
        public int IDKlienta { get; set; }
        public string Nazwisko { get; set; }
        public string Imie { get; set; }
        public string Pesel { get; set; }
        public int Wiek { get; set; }
        public string Nr_PrawaJazdy { get; set; }
        public string Ulica { get; set; }
        public int Nr_mieszkania { get; set; }
        public string Kod_Pocztowy { get; set; }
        public string Telefon { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wypozyczenia> Wypozyczenia { get; set; }
    }
}
