//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pojazdy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pojazdy()
        {
            this.Wypozyczenia = new HashSet<Wypozyczenia>();
        }
    
        public int ID_Samochodu { get; set; }
        public string Vin { get; set; }
        public string Rejestracja { get; set; }
        public string Marka { get; set; }
        public string Model { get; set; }
        public System.DateTime Rok_Produkcji { get; set; }
        public string Wersja_Silnika { get; set; }
        public int Moc { get; set; }
        public string Wersja_Wyposazenia { get; set; }
        public string Numer_Transpondera_GPS { get; set; }
        public string Rodzaj_Nadwozia { get; set; }
        public decimal Stawka { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wypozyczenia> Wypozyczenia { get; set; }
    }
}
