//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wypozyczenia
    {
        public int IDWypozyczenia { get; set; }
        public int IDKlienta { get; set; }
        public int ID_Samochodu { get; set; }
        public int KodPracownika { get; set; }
        public System.DateTime Data_Wypozyczenia { get; set; }
        public System.DateTime Data_Zwrotu { get; set; }
        public Nullable<int> Długość_wypozyczenia { get; set; }
    
        public virtual Klienci Klienci { get; set; }
        public virtual Pojazdy Pojazdy { get; set; }
        public virtual Pracownicy Pracownicy { get; set; }
    }
}
